# Shell
brew "fish"

# Version Control
brew "git"
brew "ghq"

# Editor
brew "neovim"
brew "vim"

# Version Management
brew "mise"

# CLI Tools
brew "fzf"
brew "eza"
brew "bat"

# Fonts
cask "font-plemol-jp-nf"
