{
  pkgs,
  lib,
  dotfilesDir,
  ...
}:
let
  deadnix = lib.getExe pkgs.deadnix;
  statix = lib.getExe pkgs.statix;
in
{
  # Install git hooks via Home Manager activation
  #
  # pre-commit formats and lints; the post-* hooks re-apply the configuration
  # when a change to it lands in the working tree.
  #
  # The same three tools are declared as flake checks in nix/flake/git-hooks.nix,
  # so CI runs them too. The two do not share an implementation: cachix's
  # git-hooks.nix installs its hook through `pre-commit`, and putting that in the
  # system closure costs 1.5 GiB — Python 3.14 and its module tree, none of it
  # already present — to install a shell script. Keep both lists in step by hand;
  # they are three entries long.
  home.activation.installGitHooks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        DOTFILES_DIR="${dotfilesDir}"
        if [ -d "$DOTFILES_DIR/.git" ]; then
          echo "Installing git hooks for dotfiles..."
          mkdir -p "$DOTFILES_DIR/.git/hooks"

          # Create the pre-commit hook for treefmt and the Nix linters
          cat > "$DOTFILES_DIR/.git/hooks/pre-commit" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    # Format staged files, then lint the staged Nix among them

    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
    if [ -z "$STAGED_FILES" ]; then
      exit 0
    fi

    echo "Running treefmt on staged files..."

    # Stash unstaged changes so treefmt only sees staged content,
    # preventing accidentally staging unrelated files
    STASH_NEEDED=false
    if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
      git stash --quiet --keep-index --include-untracked
      STASH_NEEDED=true
    fi

    # Run treefmt and capture exit code
    treefmt_result=0
    nix run .#fmt 2>/dev/null || treefmt_result=$?

    # Lint only the staged Nix files. deadnix takes a file list; statix takes a
    # single target, so it reads the tree and is filtered by .gitignore.
    lint_result=0
    STAGED_NIX=$(printf '%s\n' "$STAGED_FILES" | grep '\.nix$' || true)
    if [ -n "$STAGED_NIX" ]; then
      echo "Linting staged Nix files..."
      # shellcheck disable=SC2086
      ${deadnix} --fail $STAGED_NIX || lint_result=$?
      ${statix} check . || lint_result=$?
    fi

    # Re-add originally staged files (in case treefmt modified them)
    for file in $STAGED_FILES; do
      if [ -f "$file" ]; then
        git add "$file"
      fi
    done

    # Restore unstaged changes
    if [ "$STASH_NEEDED" = true ]; then
      git stash pop --quiet
    fi

    if [ $treefmt_result -ne 0 ]; then
      echo "treefmt failed"
      exit 1
    fi

    if [ $lint_result -ne 0 ]; then
      echo "deadnix/statix found problems"
      exit 1
    fi

    exit 0
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/pre-commit"

          # Create the post-commit hook for nix-apply
          cat > "$DOTFILES_DIR/.git/hooks/post-commit" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    # Skip during rebase, merge, or cherry-pick operations
    if [ -d "$(git rev-parse --git-dir)/rebase-merge" ] || \
       [ -d "$(git rev-parse --git-dir)/rebase-apply" ] || \
       [ -f "$(git rev-parse --git-dir)/MERGE_HEAD" ] || \
       [ -f "$(git rev-parse --git-dir)/CHERRY_PICK_HEAD" ]; then
      exit 0
    fi

    if git diff HEAD^..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-commit"

          # Create the post-checkout hook
          cat > "$DOTFILES_DIR/.git/hooks/post-checkout" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    # post-checkout receives: $1=prev HEAD, $2=new HEAD, $3=flag
    # Skip if just restoring files (flag=0)
    if [ "$3" = "0" ]; then
      exit 0
    fi

    # Skip during rebase operations
    if [ -d "$(git rev-parse --git-dir)/rebase-merge" ] || \
       [ -d "$(git rev-parse --git-dir)/rebase-apply" ]; then
      exit 0
    fi

    if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-checkout"

          # Create the post-merge hook
          cat > "$DOTFILES_DIR/.git/hooks/post-merge" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-merge"

          # Create the post-rewrite hook (triggered after git pull --rebase)
          cat > "$DOTFILES_DIR/.git/hooks/post-rewrite" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    # post-rewrite receives: $1=rebase or amend
    # Only run after rebase (not amend, which is handled by post-commit)
    if [ "$1" != "rebase" ]; then
      exit 0
    fi

    # Compare ORIG_HEAD (before rebase) with HEAD (after rebase)
    if git diff ORIG_HEAD..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/)'; then
      echo "Nix configuration changed after rebase. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-rewrite"

          echo "Git hooks installed successfully!"
        fi
  '';
}
