name: macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest

    steps:
      - name: Setup
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/11gather11/dotfiles/main/install)"
