name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Cellar
            /usr/local/Homebrew
            ~/.local/share/mise
            ~/.local/state/mise
          key: ${{ runner.os }}-deps-${{ hashFiles('config/homebrew/Brewfile', 'config/mise/config.toml') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Setup dotfiles
        run: bash ./install.sh
        env:
          CI: true
