name: Ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Homebrew
            /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-brew-${{ hashFiles('config/homebrew/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Setup dotfiles
        run: bash ./install.sh
        env:
          CI: true
