name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/11gather11/dotfiles/main/install)"
